### ISSUE TITLE
[Discussion] 프로젝트를 Windows 환경에 맞게 세팅

### ISSUE THREAD

**Issue by jeongjae96** [boostcampaitech3/final-project-level3-cv-09#74]
### What?

현재 사용하고 있는 컴퓨터 사양
CPU: Intel i9-10850K
GPU: NVIDIA GeForce RTX 3090 (CUDA Version: 11.5)

기존 requirements.txt.에서 사용하는 torch 버전 말고
```conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge``` 사용해서 설치.

현재 맞닥뜨린 에러

![image](https://user-images.githubusercontent.com/44770369/177935190-dfc341b2-aa56-49fc-989c-c50805403cbe.png)

어떻게 해결해야 할까?

**Comment by yoonghee** [comment]
인코딩에러는 해당 파일의
with open('assets/css/main.css') as f:

>with open('assets/css/main.css', encoding='utf-8') as f:
와 같이 변경하면 해결됩니다.

**Comment by yoonghee** [comment]
![image](https://user-images.githubusercontent.com/42772494/178095588-e3d68922-9c85-4cd6-ba93-431c9423cb58.png)
해결하고 동영상 업로드 했더니 위와 같은 에러가 생기네요ㅠㅠ

**Comment by km9mn** [comment]
현재 코드는 linux 용 path('/')를 받음
토끼굴 pc는 window '\' 라 통일하는 작업이 필요함

**Comment by jeongjae96** [comment]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\user\anaconda3\envs\hipipe\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\user\anaconda3\envs\hipipe\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\user\anaconda3\envs\hipipe\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\user\anaconda3\envs\hipipe\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\user\anaconda3\envs\hipipe\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\user\anaconda3\envs\hipipe\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\user\anaconda3\envs\hipipe\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\SGM_AI\HIPIPE\final-project-level3-cv-09\pipeline\zzolflix.py", line 26, in <module>
    app = hy.HydraApp(
  File "C:\Users\user\anaconda3\envs\hipipe\lib\site-packages\hydralit\hydra_app.py", line 184, in __init__
    self.session_state = SessionState.get(previous_app=None, selected_app=None,other_nav_app=None, preserve_state=preserve_state, allow_access=self._no_access_level,logged_in=False,access_hash=None)
  File "C:\Users\user\anaconda3\envs\hipipe\lib\site-packages\hydralit\sessionstate.py", line 69, in get
    session_id = get_script_run_ctx().session_id
AttributeError: 'NoneType' object has no attribute 'session_id'
2022-07-14 15:14:11.850 WARNING tensorflow: From C:\Users\user\anaconda3\envs\hipipe\lib\site-packages\tensorflow\python\compat\v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2022-07-14 15:14:12.577802: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 20909 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:01:00.0, compute capability: 8.6
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\user\anaconda3\envs\hipipe\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\user\anaconda3\envs\hipipe\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\user\anaconda3\envs\hipipe\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\user\anaconda3\envs\hipipe\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\user\anaconda3\envs\hipipe\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\user\anaconda3\envs\hipipe\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\user\anaconda3\envs\hipipe\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\SGM_AI\HIPIPE\final-project-level3-cv-09\pipeline\zzolflix.py", line 26, in <module>
    app = hy.HydraApp(
  File "C:\Users\user\anaconda3\envs\hipipe\lib\site-packages\hydralit\hydra_app.py", line 184, in __init__
    self.session_state = SessionState.get(previous_app=None, selected_app=None,other_nav_app=None, preserve_state=preserve_state, allow_access=self._no_access_level,logged_in=False,access_hash=None)
  File "C:\Users\user\anaconda3\envs\hipipe\lib\site-packages\hydralit\sessionstate.py", line 69, in get
    session_id = get_script_run_ctx().session_id
AttributeError: 'NoneType' object has no attribute 'session_id'
```

현재 맞닥뜨린 에러. HydraApp을 불러오는데 문제가 생기는 것으로 보인다.

**Comment by jeongjae96** [comment]
> 현재 코드는 linux 용 path('/')를 받음 토끼굴 pc는 window '' 라 통일하는 작업이 필요함

해결!

**Comment by km9mn** [comment]
slack에 linux쓰는 팀 있냐고 물어봤습니다.
근데 토끼굴 pc를 linux로 바꾼다고해도
저희가 쓸 노트북이 window라 linux서버를 사지 않는한 window에서 돌아가게 바꾸는 작업이 필요할 거 같아요

**Comment by jeongjae96** [comment]
https://docs.microsoft.com/ko-kr/virtualization/windowscontainers/quick-start/quick-start-windows-10-linux

도커로 linux 컨테이너를 띄운다면 지금 하고있는 작업을 안 해도 될 것 같다.

**Comment by yoonghee** [comment]
> ```
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Users\user\anaconda3\envs\hipipe\lib\multiprocessing\spawn.py", line 116, in spawn_main
>     exitcode = _main(fd, parent_sentinel)
>   File "C:\Users\user\anaconda3\envs\hipipe\lib\multiprocessing\spawn.py", line 125, in _main
>     prepare(preparation_data)
>   File "C:\Users\user\anaconda3\envs\hipipe\lib\multiprocessing\spawn.py", line 236, in prepare
>     _fixup_main_from_path(data['init_main_from_path'])
>   File "C:\Users\user\anaconda3\envs\hipipe\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
>     main_content = runpy.run_path(main_path,
>   File "C:\Users\user\anaconda3\envs\hipipe\lib\runpy.py", line 265, in run_path
>     return _run_module_code(code, init_globals, run_name,
>   File "C:\Users\user\anaconda3\envs\hipipe\lib\runpy.py", line 97, in _run_module_code
>     _run_code(code, mod_globals, init_globals,
>   File "C:\Users\user\anaconda3\envs\hipipe\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\SGM_AI\HIPIPE\final-project-level3-cv-09\pipeline\zzolflix.py", line 26, in <module>
>     app = hy.HydraApp(
>   File "C:\Users\user\anaconda3\envs\hipipe\lib\site-packages\hydralit\hydra_app.py", line 184, in __init__
>     self.session_state = SessionState.get(previous_app=None, selected_app=None,other_nav_app=None, preserve_state=preserve_state, allow_access=self._no_access_level,logged_in=False,access_hash=None)
>   File "C:\Users\user\anaconda3\envs\hipipe\lib\site-packages\hydralit\sessionstate.py", line 69, in get
>     session_id = get_script_run_ctx().session_id
> AttributeError: 'NoneType' object has no attribute 'session_id'
> 2022-07-14 15:14:11.850 WARNING tensorflow: From C:\Users\user\anaconda3\envs\hipipe\lib\site-packages\tensorflow\python\compat\v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
> Instructions for updating:
> non-resource variables are not supported in the long term
> 2022-07-14 15:14:12.577802: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 20909 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:01:00.0, compute capability: 8.6
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Users\user\anaconda3\envs\hipipe\lib\multiprocessing\spawn.py", line 116, in spawn_main
>     exitcode = _main(fd, parent_sentinel)
>   File "C:\Users\user\anaconda3\envs\hipipe\lib\multiprocessing\spawn.py", line 125, in _main
>     prepare(preparation_data)
>   File "C:\Users\user\anaconda3\envs\hipipe\lib\multiprocessing\spawn.py", line 236, in prepare
>     _fixup_main_from_path(data['init_main_from_path'])
>   File "C:\Users\user\anaconda3\envs\hipipe\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
>     main_content = runpy.run_path(main_path,
>   File "C:\Users\user\anaconda3\envs\hipipe\lib\runpy.py", line 265, in run_path
>     return _run_module_code(code, init_globals, run_name,
>   File "C:\Users\user\anaconda3\envs\hipipe\lib\runpy.py", line 97, in _run_module_code
>     _run_code(code, mod_globals, init_globals,
>   File "C:\Users\user\anaconda3\envs\hipipe\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\SGM_AI\HIPIPE\final-project-level3-cv-09\pipeline\zzolflix.py", line 26, in <module>
>     app = hy.HydraApp(
>   File "C:\Users\user\anaconda3\envs\hipipe\lib\site-packages\hydralit\hydra_app.py", line 184, in __init__
>     self.session_state = SessionState.get(previous_app=None, selected_app=None,other_nav_app=None, preserve_state=preserve_state, allow_access=self._no_access_level,logged_in=False,access_hash=None)
>   File "C:\Users\user\anaconda3\envs\hipipe\lib\site-packages\hydralit\sessionstate.py", line 69, in get
>     session_id = get_script_run_ctx().session_id
> AttributeError: 'NoneType' object has no attribute 'session_id'
> ```
> 
> 현재 맞닥뜨린 에러. HydraApp을 불러오는데 문제가 생기는 것으로 보인다.

여기 에러나는 부분 Dataloading - 0 이부분만 잘 동작하는지 테스트해본 결과
![image](https://user-images.githubusercontent.com/42772494/179388321-567e4784-6804-4ca1-b9f4-f0d388aa0046.png)
위와 같은 에러가 발생하였고, 검색해보니 image나 mp4파일을
윈도우에서 여러 프로세스 접속시 나타나는 permission관련 에러라네요.. 

해당 문제 발생 시 강제종료등의 이슈가 발생한다는 걸로 보아
윈도우 권한 관련 에러인걸로 파악됩니다.

해결법은 window에서 linux로 변경해서 실행하는 것과, 파일 open을 하기전에 close하는 방법등이 있다던데 더 검색해봐야 될 것 같습니다.

**Comment by jeongjae96** [comment]
data loading하는 부분에서도 경로 문제가 발생한다. 하드코딩되어 있는 부분이 꽤 있어서 수정을 전체적으로 해야할듯하다.
